package com.example.ui.theme

import com.example.data.model.AppLanguage

object AppStrings {
    fun get(key: String, language: AppLanguage): String {
        val strings = when (language) {
            AppLanguage.ARABIC -> arStrings
            AppLanguage.ENGLISH -> enStrings
            AppLanguage.TURKISH -> trStrings
        }
        return strings[key] ?: key
    }

    private val arStrings = mapOf(
        "app_name" to "وصلني",
        "search" to "البحث",
        "my_rides" to "رحلاتي",
        "publish" to "نشر رحلة",
        "messages" to "الرسائل",
        "conversations" to "المحادثات",
        "requested_trips" to "الطلبات",
        "my_wallet" to "محفظتي",
        "admin_panel" to "لوحة الأدمن",
        "settings" to "الإعدادات",
        "language" to "اللغة",
        "dark_mode" to "الوضع المظلم",
        "login" to "تسجيل الدخول",
        "register" to "إنشاء حساب جديد",
        "logout" to "تسجيل الخروج",
        "phone_number" to "رقم الهاتف",
        "email" to "البريد الإلكتروني",
        "full_name" to "الاسم الكامل",
        "password" to "كلمة السر",
        "forgot_password" to "نسيت كلمة السر؟",
        "reset_password" to "إعادة تعيين كلمة السر",
        "verify_phone" to "تأكيد رقم الهاتف",
        "enter_otp" to "أدخل رمز التحقق (OTP) المرسل لهاتفك",
        "confirm_otp" to "تأكيد الرمز",
        "rate_user" to "تقييم الحساب",
        "submit_rating" to "إرسال التقييم",

        // Search Screen
        "from" to "من (نقطة الانطلاق)",
        "to" to "إلى (الوجهة)",
        "date" to "التاريخ",
        "time" to "الوقت",
        "passengers" to "عدد الركاب",
        "search_rides" to "ابحث عن رحلة",
        "suggested_rides" to "رحلات قريبة ومقترحة",
        "select_city" to "اختر المدينة",
        "swap" to "تبديل",

        // Results
        "filters" to "الفلاتر",
        "all" to "الكل",
        "verified_only" to "سائقون موثقون",
        "women_only" to "للنساء فقط",
        "rating_4plus" to "تقييم 4.5+",
        "seats_left" to "مقاعد متبقية",
        "per_seat" to "لكل مقعد",
        "book_now" to "احجز الآن",
        "no_rides_found" to "لم يتم العثور على رحلات متطابقة",

        // Ride Details
        "ride_details" to "تفاصيل الرحلة",
        "route_map" to "خريطة المسار ونقطة الالتقاء",
        "driver_info" to "معلومات السائق",
        "car_info" to "تفاصيل السيارة",
        "amenities" to "مميزات الرحلة",
        "luggage_allowed" to "يسمح بالأمتعة",
        "cash_payment" to "دفع نقدي",
        "wallet_payment" to "دفع عبر المحفظة",
        "verified_driver" to "سائق موثق بالهوية",
        "trip_count" to "رحلة مكتملة",
        "driver_status" to "حالة السائق",
        "rate_driver" to "تقييم السائق",
        "driver_active_ready" to "نشط ومستعد للرحلة",
        "rating_dialog_title" to "تقييم السائق",
        "rating_dialog_desc" to "شاركنا تقييمك لتجربة السفر مع هذا السائق لتحسين الجودة ودعم السائقين المتميزين.",
        "select_rating_stars" to "اختر التقييم بالنجوم:",
        "add_review_comment" to "ملاحظة أو كلمة شكر للسائق (اختياري):",
        "review_placeholder" to "اكتب تعليقك أو انطباعك هنا...",
        "rating_tags_title" to "أبرز مميزات الرحلة:",
        "tag_punctual" to "⏰ دقيق بالمواعيد",
        "tag_safe_driving" to "🚗 سياقة آمنة وهادئة",
        "tag_clean_car" to "✨ سيارة نظيفة ومريحة",
        "tag_polite" to "🤝 تعامل محترم ولبق",
        "tag_responsive" to "💬 تواصل ممتاز وسريع",
        "submit_rating_success" to "تم إرسال تقييمك بنجاح! شكراً لمساهمتك ⭐",
        "confirm_booking" to "تأكيد الحجز",
        "booking_success" to "تم حجز الرحلة بنجاح!",

        // My Rides
        "as_driver" to "رحلاتي كسائق",
        "as_passenger" to "رحلاتي كراكب",
        "upcoming" to "قادمة",
        "completed" to "منتهية",
        "cancelled" to "ملغاة",
        "cancel_ride" to "إلغاء الرحلة",
        "edit_ride" to "تعديل الرحلة",
        "cancel_confirm" to "هل أنت أصلًا متأكد من إلغاء هذه الرحلة؟",
        "cancel_success" to "تم إلغاء الرحلة بنجاح",

        // Publish Ride
        "start_point" to "نقطة البداية",
        "destination" to "الوجهة",
        "available_seats" to "عدد المقاعد الشاغرة",
        "suggested_price" to "السعر المقترح لكل مقعد ($)",
        "publish_button" to "نشر الرحلة",
        "publish_cost_note" to "ملاحظة: يتطلب نشر كل رحلة خصم 50 نقطة من محفظتك فوراً.",
        "insufficient_balance" to "رصيدك غير كافٍ، يرجى شحن المحفظة",
        "insufficient_balance_msg" to "يتطلب نشر الرحلة 50 نقطة ورصيدك الحالي أقل من ذلك. يرجى الانتقال للمحفظة لشحن الرصيد.",
        "topup_now" to "شحن المحفظة الآن",
        "publish_success" to "تم نشر الرحلة بنجاح وخصم 50 نقطة!",

        // Wallet & Packages
        "current_points" to "رصيد النقاط الحالي",
        "points" to "نقطة",
        "topup_balance" to "شحن الرصيد",
        "transaction_history" to "سجل العمليات",
        "select_package" to "اختر باقة النقاط المناسبة",
        "buy_now" to "اشترِ الآن",
        "package_50" to "50 نقطة بسعر 0.50 دولار",
        "package_100" to "100 نقطة بسعر 0.75 دولار",
        "package_200" to "200 نقطة بسعر 1.75 دولار",
        "package_500" to "500 نقطة بسعر 4.00 دولار",

        // Cham Cash Modal
        "cham_cash_payment" to "الدفع عبر شام كاش (Cham Cash)",
        "account_number" to "رقم حساب شام كاش الموحد للمشغل:",
        "fixed_cham_account" to "ba64858e96d4ad9c6096948bc2dbc970",
        "copy_account" to "نسخ الرقم",
        "account_copied" to "تم نسخ رقم حساب شام كاش بنجاح!",
        "instructions" to "قم بتحويل المبلغ المطلوب إلى حساب شام كاش أعلاه، ثم ارفق صورة إشعار الدفع.",
        "upload_receipt" to "رفع صورة الإشعار",
        "receipt_selected" to "تم إرفاق صورة الإشعار بنجاح",
        "submit_request" to "تقديم الطلب",
        "request_under_review" to "طلبك قيد المراجعة حالياً",

        // Chat
        "chat_with" to "المحادثة مع",
        "type_message" to "اكتب رسالة...",
        "send" to "إرسال",
        "attach_photo" to "إرفاق صورة",
        "share_location" to "مشاركة الموقع المباشر",
        "payment_reminder" to "تذكير: يرجى تحويل مبلغ الرحلة للسائق بعد الوصول.",

        // Admin
        "admin_title" to "لوحة تحكم الأدمن",
        "total_revenue" to "إجمالي الإيرادات",
        "total_users" to "المستخدمين",
        "total_published_rides" to "الرحلات المنشورة",
        "total_points_sold" to "النقاط المباعة",
        "incoming_requests" to "طلبات الشحن الواردة",
        "approve" to "تأكيد الدفع",
        "reject" to "رفض الدفع",
        "rejection_reason" to "سبب الرفض (اختياري)",
        "backup_db" to "نسخ احتياطي لقاعدة البيانات",
        "backup_success" to "تم إنشاء نسخة احتياطية بنجاح!",

        // Notifications
        "notifications" to "الإشعارات",
        "no_notifications" to "لا توجد إشعارات حالياً"
    )

    private val enStrings = mapOf(
        "app_name" to "Wasalni (وصلني)",
        "search" to "Search",
        "my_rides" to "My Rides",
        "publish" to "Publish",
        "messages" to "Messages",
        "my_wallet" to "My Wallet",
        "admin_panel" to "Admin Panel",
        "settings" to "Settings",
        "language" to "Language",
        "dark_mode" to "Dark Mode",

        "from" to "From (Origin)",
        "to" to "To (Destination)",
        "date" to "Date",
        "time" to "Time",
        "passengers" to "Passengers",
        "search_rides" to "Search Rides",
        "suggested_rides" to "Nearby & Suggested Rides",
        "select_city" to "Select City",
        "swap" to "Swap",

        "filters" to "Filters",
        "all" to "All",
        "verified_only" to "Verified Drivers",
        "women_only" to "Women Only",
        "rating_4plus" to "Rating 4.5+",
        "seats_left" to "seats left",
        "per_seat" to "per seat",
        "book_now" to "Book Now",
        "no_rides_found" to "No matching rides found",

        "ride_details" to "Ride Details",
        "route_map" to "Route & Pickup Map",
        "driver_info" to "Driver Info",
        "car_info" to "Vehicle Details",
        "amenities" to "Amenities",
        "luggage_allowed" to "Luggage Allowed",
        "cash_payment" to "Cash Payment",
        "wallet_payment" to "Wallet Payment",
        "verified_driver" to "ID Verified Driver",
        "trip_count" to "completed trips",
        "driver_status" to "Driver Status",
        "rate_driver" to "Rate Driver",
        "driver_active_ready" to "Active & Ready for Ride",
        "rating_dialog_title" to "Rate Driver",
        "rating_dialog_desc" to "Share your feedback about traveling with this driver to support top drivers and improve ride quality.",
        "select_rating_stars" to "Select rating score:",
        "add_review_comment" to "Optional driver note or comment:",
        "review_placeholder" to "Write your feedback here...",
        "rating_tags_title" to "Trip Highlights:",
        "tag_punctual" to "⏰ On Time",
        "tag_safe_driving" to "🚗 Safe & Smooth Driving",
        "tag_clean_car" to "✨ Clean & Comfortable Car",
        "tag_polite" to "🤝 Polite & Respectful",
        "tag_responsive" to "💬 Fast Communication",
        "submit_rating_success" to "Thank you! Your driver rating was submitted ⭐",
        "confirm_booking" to "Confirm Booking",
        "booking_success" to "Ride booked successfully!",

        "as_driver" to "As Driver",
        "as_passenger" to "As Passenger",
        "upcoming" to "Upcoming",
        "completed" to "Completed",
        "cancelled" to "Cancelled",
        "cancel_ride" to "Cancel Ride",
        "edit_ride" to "Edit Ride",
        "cancel_confirm" to "Are you sure you want to cancel this ride?",
        "cancel_success" to "Ride cancelled successfully",

        "start_point" to "Start Point",
        "destination" to "Destination",
        "available_seats" to "Available Seats",
        "suggested_price" to "Suggested Price / Seat ($)",
        "publish_button" to "Publish Ride",
        "publish_cost_note" to "Note: Publishing a ride immediately costs 50 wallet points.",
        "insufficient_balance" to "Insufficient points, please top up your wallet",
        "insufficient_balance_msg" to "Publishing a ride requires 50 points. Your balance is too low. Please top up your wallet.",
        "topup_now" to "Top Up Wallet Now",
        "publish_success" to "Ride published! 50 points deducted.",

        "current_points" to "Current Points Balance",
        "points" to "Pts",
        "topup_balance" to "Top Up Balance",
        "transaction_history" to "Transaction History",
        "select_package" to "Select Points Package",
        "buy_now" to "Buy Now",
        "package_50" to "50 Points for $0.50",
        "package_100" to "100 Points for $0.75",
        "package_200" to "200 Points for $1.75",
        "package_500" to "500 Points for $4.00",

        "cham_cash_payment" to "Cham Cash Payment",
        "account_number" to "Fixed Operator Cham Cash Account:",
        "fixed_cham_account" to "ba64858e96d4ad9c6096948bc2dbc970",
        "copy_account" to "Copy Account",
        "account_copied" to "Cham Cash Account copied to clipboard!",
        "instructions" to "Transfer the required amount to the Cham Cash account above, then attach the receipt screenshot.",
        "upload_receipt" to "Upload Receipt Image",
        "receipt_selected" to "Payment receipt attached successfully",
        "submit_request" to "Submit Request",
        "request_under_review" to "Your request is currently under review",

        "chat_with" to "Chat with",
        "type_message" to "Type a message...",
        "send" to "Send",
        "attach_photo" to "Attach Photo",
        "share_location" to "Share Live Location",
        "payment_reminder" to "Reminder: Please pay the driver upon arrival.",

        "admin_title" to "Admin Dashboard",
        "total_revenue" to "Total Revenue",
        "total_users" to "Users",
        "total_published_rides" to "Published Rides",
        "total_points_sold" to "Points Sold",
        "incoming_requests" to "Top-Up Requests",
        "approve" to "Approve Payment",
        "reject" to "Reject Payment",
        "rejection_reason" to "Rejection Reason (Optional)",
        "backup_db" to "Backup Database",
        "backup_success" to "Database backed up successfully!",

        "notifications" to "Notifications",
        "no_notifications" to "No notifications yet"
    )

    private val trStrings = mapOf(
        "app_name" to "BlaBlaRide",
        "search" to "Ara",
        "my_rides" to "Yolculuklarım",
        "publish" to "Yayınla",
        "messages" to "Mesajlar",
        "my_wallet" to "Cüzdanım",
        "admin_panel" to "Yönetici Paneli",
        "settings" to "Ayarlar",
        "language" to "Dil",
        "dark_mode" to "Karanlık Mod",

        "from" to "Nereden",
        "to" to "Nereye",
        "date" to "Tarih",
        "time" to "Saat",
        "passengers" to "Yolcu Sayısı",
        "search_rides" to "Yolculuk Ara",
        "suggested_rides" to "Yakındaki ve Önerilen Yolculuklar",
        "select_city" to "Şehir Seç",
        "swap" to "Değiştir",

        "filters" to "Filtreler",
        "all" to "Tümü",
        "verified_only" to "Doğrulanmış Sürücüler",
        "women_only" to "Sadece Kadınlar",
        "rating_4plus" to "Puan 4.5+",
        "seats_left" to "koltuk kaldı",
        "per_seat" to "koltuk başı",
        "book_now" to "Şimdi Rezerve Et",
        "no_rides_found" to "Eşleşen yolculuk bulunamadı",

        "ride_details" to "Yolculuk Detayları",
        "route_map" to "Rota ve Buluşma Haritası",
        "driver_info" to "Sürücü Bilgileri",
        "car_info" to "Araç Detayları",
        "amenities" to "Özellikler",
        "luggage_allowed" to "Bagaja İzin Verilir",
        "cash_payment" to "Nakit Ödeme",
        "wallet_payment" to "Cüzdan Ödemesi",
        "verified_driver" to "Kimliği Doğrulanmış Sürücü",
        "trip_count" to "tamamlanan yolculuk",
        "driver_status" to "Sürücü Durumu",
        "rate_driver" to "Sürücüyü Değerlendir",
        "driver_active_ready" to "Aktif ve Yolculuğa Hazır",
        "rating_dialog_title" to "Sürücüyü Değerlendir",
        "rating_dialog_desc" to "Bu sürücüyle seyahat deneyiminizi değerlendirin.",
        "select_rating_stars" to "Yıldız puanı seçin:",
        "add_review_comment" to "Sürücüye not veya yorum ekleyin (isteğe bağlı):",
        "review_placeholder" to "Yorumunuzu buraya yazın...",
        "rating_tags_title" to "Öne Çıkanlar:",
        "tag_punctual" to "⏰ Zamanında",
        "tag_safe_driving" to "🚗 Güvenli Sürüş",
        "tag_clean_car" to "✨ Temiz ve Konforlu Araç",
        "tag_polite" to "🤝 Saygılı ve Nazik",
        "tag_responsive" to "💬 Hızlı İletişim",
        "submit_rating_success" to "Sürücü değerlendirmeniz başarıyla gönderildi ⭐",
        "confirm_booking" to "Rezervasyonu Onayla",
        "booking_success" to "Yolculuk başarıyla rezerve edildi!",

        "as_driver" to "Sürücü Olarak",
        "as_passenger" to "Yolcu Olarak",
        "upcoming" to "Yaklaşan",
        "completed" to "Tamamlandı",
        "cancelled" to "İptal Edildi",
        "cancel_ride" to "Yolculuğu İptal Et",
        "edit_ride" to "Düzenle",
        "cancel_confirm" to "Bu yolculuğu iptal etmek istediğinizden emin misiniz?",
        "cancel_success" to "Yolculuk başarıyla iptal edildi",

        "start_point" to "Başlangıç Noktası",
        "destination" to "Varış Noktası",
        "available_seats" to "Boş Koltuk Sayısı",
        "suggested_price" to "Koltuk Başı Fiyat ($)",
        "publish_button" to "Yolculuğu Yayınla",
        "publish_cost_note" to "Not: Bir yolculuk yayınlamak 50 puan gerektirir.",
        "insufficient_balance" to "Yetersiz bakiye, lütfen cüzdanınızı doldurun",
        "insufficient_balance_msg" to "Yolculuk yayınlamak için 50 puan gereklidir. Bakiyeniz yetersizdir.",
        "topup_now" to "Şimdi Yükle",
        "publish_success" to "Yolculuk yayınlandı! 50 puan düşüldü.",

        "current_points" to "Mevcut Puan Bakiyesi",
        "points" to "Puan",
        "topup_balance" to "Bakiye Yükle",
        "transaction_history" to "İşlem Geçmişi",
        "select_package" to "Puan Paketini Seçin",
        "buy_now" to "Satın Al",
        "package_50" to "50 Puan - 0.50$",
        "package_100" to "100 Puan - 0.75$",
        "package_200" to "200 Puan - 1.75$",
        "package_500" to "500 Puan - 4.00$",

        "cham_cash_payment" to "Cham Cash ile Ödeme",
        "account_number" to "Sabit Cham Cash Hesap Numarası:",
        "fixed_cham_account" to "ba64858e96d4ad9c6096948bc2dbc970",
        "copy_account" to "Numarayı Kopyala",
        "account_copied" to "Cham Cash hesap numarası kopyalandı!",
        "instructions" to "Gerekli tutarı yukarıdaki Cham Cash hesabına transfer edin ve dekont fotoğrafını ekleyin.",
        "upload_receipt" to "Dekont Fotoğrafı Yükle",
        "receipt_selected" to "Dekont fotoğrafı başarıyla eklendi",
        "submit_request" to "Talebi Gönder",
        "request_under_review" to "Talebiniz inceleme aşamasındadır",

        "chat_with" to "Sohbet:",
        "type_message" to "Bir mesaj yazın...",
        "send" to "Gönder",
        "attach_photo" to "Fotoğraf Ekle",
        "share_location" to "Canlı Konum Paylaş",
        "payment_reminder" to "Hatırlatma: Lütfen varışta sürücüye ücreti ödeyin.",

        "admin_title" to "Yönetici Paneli",
        "total_revenue" to "Toplam Gelir",
        "total_users" to "Kullanıcılar",
        "total_published_rides" to "Yayınlanan Yolculuklar",
        "total_points_sold" to "Satılan Puanlar",
        "incoming_requests" to "Gelen Yükleme Talepleri",
        "approve" to "Ödemeyi Onayla",
        "reject" to "Ödemeyi Reddet",
        "rejection_reason" to "Reddetme Nedeni (İsteğe Bağlı)",
        "backup_db" to "Veritabanını Yedekle",
        "backup_success" to "Veritabanı başarıyla yedeklendi!",

        "notifications" to "Bildirimler",
        "no_notifications" to "Henüz bildirim yok"
    )
}
